paths:
  data_dir: images/
  save_dir: results/
params:
  batch_size: 1000
  epochs: 10
  lr: 0.001
  n_conv_channels: 32
  n_linear_out_channels: 100
  learn_bias: true
mlflow_uri: "http://127.0.0.1:8080"
